import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Filters from '@/components/Filters';
import Image from 'next/image';
import { Spotlight } from '@/components/ui/Spotlight';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
            <Spotlight
        className="-top-40 left-0 md:left-60 md:-top-20"
        fill="black"
      />
                <div className='bg-zinc-200 pt-5'>
                <img src='https://taniarascia.github.io/sandbox/ghibli/logo.png' alt='logo ghibli' className='mx-auto bg-zinc-200' />
                <div className=' '>{children}</div>
                </div>
            </body>
        </html>
    );
}
